import type { TemporalEvidence, TemporalEvidenceConfidence, TemporalEvidenceDiagnostics, TemporalEvidencePrecision, TemporalEvidenceStatistics, TemporalEvidenceType } from "@/contracts/temporal";

type TemporalEvidenceInput = Readonly<{ entityId: string; sourceEntityId: string; providerId: string; type: TemporalEvidenceType; timestamp: string | undefined; referenceId: string; confidence?: TemporalEvidenceConfidence }>;

function precisionFor(value: string): TemporalEvidencePrecision { return /^\d{4}-\d{2}-\d{2}$/.test(value) ? "date" : /\.\d{3}Z$/.test(value) ? "millisecond" : /:\d{2}Z$/.test(value) ? "second" : /T\d{2}:\d{2}Z$/.test(value) ? "minute" : "unknown"; }
function validTimestamp(value: string) { return /^\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}(?::\d{2}(?:\.\d{3})?)?Z)?$/.test(value) && !Number.isNaN(Date.parse(value)); }
export function temporalEvidenceFromSourceMetadata(input: TemporalEvidenceInput): { evidence?: TemporalEvidence; diagnostics: readonly TemporalEvidenceDiagnostics[] } {
  if (!input.timestamp) return { diagnostics: Object.freeze([{ code: "timestamp-missing", message: `Temporal evidence missing timestamp for ${input.sourceEntityId}` }]) };
  if (!validTimestamp(input.timestamp)) return { diagnostics: Object.freeze([{ code: "timestamp-invalid", message: `Temporal evidence invalid timestamp for ${input.sourceEntityId}` }]) };
  const id = `temporal:${input.providerId}:${input.sourceEntityId}:${input.type}:${input.timestamp}:${input.referenceId}`;
  const diagnostics = Object.freeze([{ code: "temporal-evidence-preserved" as const, message: `Temporal evidence preserved for ${input.sourceEntityId}` }]);
  return { evidence: Object.freeze({ id, entityId: input.entityId, sourceEntityId: input.sourceEntityId, providerId: input.providerId, type: input.type, timestamp: input.timestamp, timestampCategory: "source-metadata", precision: precisionFor(input.timestamp), source: "source", reference: Object.freeze({ id: input.referenceId, kind: "source-metadata" }), confidence: input.confidence ?? "observed", diagnostics }), diagnostics };
}
export function summarizeTemporalEvidence(evidence: readonly TemporalEvidence[], runtime: Readonly<{ observationsCreated?: number; status?: "ready" | "ready-empty" }> = {}): TemporalEvidenceStatistics { return Object.freeze({ providerCount: new Set(evidence.map((item) => item.providerId)).size, evidenceCount: evidence.length, memoryEligibleCount: evidence.filter((item) => item.timestampCategory === "source-event" || item.timestampCategory === "source-metadata").length, sourceEventCount: evidence.filter((item) => item.timestampCategory === "source-event").length, sourceMetadataCount: evidence.filter((item) => item.timestampCategory === "source-metadata").length, providerObservationCount: evidence.filter((item) => item.timestampCategory === "provider-observation").length, runtimeProcessingCount: evidence.filter((item) => item.timestampCategory === "runtime-processing").length, entityCount: new Set(evidence.map((item) => item.entityId)).size, observationsCreated: runtime.observationsCreated ?? 0, readySessionCount: runtime.status === "ready" ? 1 : 0, readyEmptySessionCount: runtime.status === "ready-empty" ? 1 : 0 }); }
