"""Stable public contracts for the Atlas runtime."""

ATLAS_RUNTIME_VERSION = "1.0.0"
ATLAS_PROVIDER_CONTRACT_VERSION = "1.0"
ATLAS_CONTEXT_PACKAGE_VERSION = "1.0"

ATLAS_MAX_CONTEXT_METADATA_ITEMS = 16
ATLAS_MAX_CONTEXT_METADATA_VALUE_CHARS = 256
ATLAS_MAX_CONTEXT_PACKAGE_BYTES = 131_072
ATLAS_MAX_PROVIDER_RESULT_BYTES = 32_768
