import type { AIModelAdapter, AIModelAdapterError, AIModelAdapterResult, AIModelRuntimeAttempt, AIModelRuntimeDiagnostic, AIModelRuntimeLimits, AIModelRuntimePolicy, AIModelRuntimeRequest, AIModelRuntimeResult } from "@/contracts/model-runtime";
import { AIModelAdapterRegistry } from "./AIModelAdapterRegistry";
const freeze=<T>(v:T):T=>{if(v&&typeof v==="object"&&!Object.isFrozen(v)){Object.freeze(v);Object.values(v as Record<string,unknown>).forEach(freeze);}return v;};
export const defaultAIModelRuntimePolicy:AIModelRuntimePolicy=freeze({allowExecution:true,allowRetries:false,allowFallbacks:true,allowStreaming:false,allowBatch:false,allowDegradedAdapters:false,stopOnCancellation:true,stopOnTimeout:false,retryableErrorCategories:["transport","rate-limit","capacity"],fallbackEligibleErrorCategories:["unavailable","timeout","transport","rate-limit","capacity","provider-error"],requirePlanPolicyCompliance:true,requireAdapterCompatibility:true,requireSourceValidation:true});
export const defaultAIModelRuntimeLimits:AIModelRuntimeLimits=freeze({timeoutMs:120000,maxRetriesPerModel:0,maxTotalAttempts:3,maxFallbackAttempts:2,maxDiagnostics:100,maxAttemptRecords:20,maxOutputCharacters:100000,maxStructuredOutputBytes:100000,maxCitationCount:100});
const error=(category:AIModelAdapterError["category"],message:string,retryable=false,fallbackEligible=false):AIModelAdapterError=>freeze({code:`runtime-${category}`,category,retryable,fallbackEligible,message});
const safeError=(value:unknown):AIModelAdapterError=> error("unknown", value instanceof Error ? value.message.replace(/\n|at\s+.+/g," ").slice(0,240) : "Adapter execution failed");
export class AIModelRuntime {
  constructor(private readonly executableAdapters: AIModelAdapterRegistry) {}
  async execute(request:AIModelRuntimeRequest):Promise<AIModelRuntimeResult> {
    const started=Date.now(), plan=request.executionPlan, diagnostics:AIModelRuntimeDiagnostic[]=[]; const attempts:AIModelRuntimeAttempt[]=[];
    const finish=(status:AIModelRuntimeResult["status"],output?:AIModelAdapterResult["output"],modelId?:string,adapterId?:string):AIModelRuntimeResult=>freeze({executionId:request.executionId,status,planId:plan.id,planFingerprint:plan.fingerprint,completedModelId:modelId,completedAdapterId:adapterId,output,attempts,diagnostics:diagnostics.slice(0,effectiveLimits.maxDiagnostics),statistics:{plannedModelCount:1+plan.fallbacks.candidates.length,attemptCount:attempts.length,retryCount:attempts.filter(a=>a.retryIndex>0).length,fallbackCount:attempts.filter(a=>a.fallbackIndex>0).length,successCount:attempts.filter(a=>a.status==="succeeded").length,failureCount:attempts.filter(a=>a.status==="failed"||a.status==="timed-out").length,durationMs:Date.now()-started},metadata:{adapterRegistryId:request.adapterRegistry.registryId,adapterRegistryVersion:request.adapterRegistry.version},fingerprint:`runtime-1:${request.executionId}:${plan.fingerprint}:${status}:${attempts.map(a=>a.attemptId).join(",")}`});
    const effectivePolicy=freeze({...defaultAIModelRuntimePolicy,...request.runtimePolicy,allowStreaming:Boolean(request.runtimePolicy?.allowStreaming&&plan.policy.allowStreaming),allowBatch:Boolean(request.runtimePolicy?.allowBatch&&plan.policy.allowBatch),allowFallbacks:Boolean(request.runtimePolicy?.allowFallbacks!==false&&plan.policy.fallbackAllowed)});
    const effectiveLimits=freeze({...defaultAIModelRuntimeLimits,...request.runtimeLimits,timeoutMs:Math.min(request.runtimeLimits?.timeoutMs??defaultAIModelRuntimeLimits.timeoutMs,plan.limits.timeoutMs),maxRetriesPerModel:Math.min(request.runtimeLimits?.maxRetriesPerModel??0,plan.limits.maxRetries),maxFallbackAttempts:Math.min(request.runtimeLimits?.maxFallbackAttempts??defaultAIModelRuntimeLimits.maxFallbackAttempts,plan.limits.maxFallbackCandidates)});
    const invalid=Object.values(effectiveLimits).some(v=>!Number.isFinite(v)||v<0||!Number.isInteger(v)); if(invalid) return finish("rejected");
    if(request.abortSignal?.aborted) {diagnostics.push({code:"cancelled",message:"Execution cancelled before validation"});return finish("cancelled");}
    if(!effectivePolicy.allowExecution||!plan.steps.length||plan.steps.length!==1||plan.steps[0].type!=="model-execution"||plan.steps[0].modelId!==plan.primary.modelId) {diagnostics.push({code:"invalid-plan",message:"Execution plan is not executable"});return finish("rejected");}
    if((request.expectedPlanId&&request.expectedPlanId!==plan.id)||(request.expectedPlanFingerprint&&request.expectedPlanFingerprint!==plan.fingerprint)||(request.expectedContextPackageId&&request.expectedContextPackageId!==plan.contextPackageId)||(request.expectedRegistryVersion&&request.expectedRegistryVersion!==plan.registryVersion)){diagnostics.push({code:"stale-plan",message:"Execution plan source reference is stale"});return finish("stale");}
    const sequence=[plan.primary,...(effectivePolicy.allowFallbacks?plan.fallbacks.candidates.slice(0,effectiveLimits.maxFallbackAttempts):[])]; let total=0;
    for(let fallbackIndex=0;fallbackIndex<sequence.length;fallbackIndex++) { const model=sequence[fallbackIndex]; let retry=0; let last:AIModelAdapterResult|undefined;
      do { if(request.abortSignal?.aborted){diagnostics.push({code:"cancelled",message:"Execution cancelled",modelId:model.modelId});return finish("cancelled");} if(total>=effectiveLimits.maxTotalAttempts) return finish("failed"); total++;
        const adapter=this.executableAdapters.resolve({modelId:model.modelId,providerType:model.providerType,location:model.location,mode:plan.steps[0].mode}); const attemptId=`${request.executionId}:attempt:${total}`;
        if(!adapter){attempts.push(freeze({attemptId,sequence:total,modelId:model.modelId,status:"incompatible-adapter",retryIndex:retry,fallbackIndex,durationMs:0}));diagnostics.push({code:"adapter-unavailable",message:"No compatible adapter",attemptId,modelId:model.modelId});break;}
        const caught = (value: unknown): AIModelAdapterResult => ({status:"failed",adapterId:adapter.descriptor.adapterId,modelId:model.modelId,error:safeError(value),diagnostics:[],metadata:{},startedAt:"",completedAt:"",durationMs:0});
        last=await this.run(adapter,request,model,attemptId,effectiveLimits.timeoutMs).catch(caught);
        const result=last; const status=result.status==="succeeded"?"succeeded":result.status==="timed-out"?"timed-out":result.status==="cancelled"?"cancelled":"failed"; attempts.push(freeze({attemptId,sequence:total,modelId:model.modelId,adapterId:adapter.descriptor.adapterId,status,retryIndex:retry,fallbackIndex,error:result.error,usage:result.usage,durationMs:result.durationMs}));
        if(result.status==="succeeded"&&result.output) return finish("succeeded",result.output,model.modelId,adapter.descriptor.adapterId); if(result.status==="cancelled"||request.abortSignal?.aborted) return finish("cancelled"); retry++;
      } while(Boolean(last?.error?.retryable)&&effectivePolicy.allowRetries&&retry<=effectiveLimits.maxRetriesPerModel);
      if(!last?.error?.fallbackEligible || !effectivePolicy.fallbackEligibleErrorCategories.includes(last.error.category)) break;
    } return finish(attempts.some(a=>a.status==="timed-out")?"timed-out":"failed");
  }
  private async run(adapter:AIModelAdapter,request:AIModelRuntimeRequest,model:AIModelRuntimeRequest["executionPlan"]["primary"],attemptId:string,timeoutMs:number):Promise<AIModelAdapterResult>{ const controller=new AbortController(); const cancel=()=>controller.abort(); request.abortSignal?.addEventListener("abort",cancel,{once:true}); let timer:ReturnType<typeof setTimeout>; const timeout=new Promise<AIModelAdapterResult>(resolve=>{timer=setTimeout(()=>{controller.abort();resolve({status:"timed-out",adapterId:adapter.descriptor.adapterId,modelId:model.modelId,error:error("timeout","Adapter execution timed out",false,true),diagnostics:[],metadata:{},startedAt:"",completedAt:"",durationMs:timeoutMs});},timeoutMs);}); try{return await Promise.race([adapter.execute({executionId:request.executionId,attemptId,requestId:request.executionId,planId:request.executionPlan.id,modelId:model.modelId,providerType:model.providerType,task:request.executionPlan.task,expectedOutputType:request.executionPlan.steps[0].outputType,executionMode:request.executionPlan.steps[0].mode,contextPackageReference:{id:request.executionPlan.contextPackageId,fingerprint:request.executionPlan.contextFingerprint},effectivePolicy:request.executionPlan.policy,limits:{timeoutMs,maxOutputCharacters:100000},adapterInput:request.adapterInput,metadata:{},signal:controller.signal}),timeout]);} finally {clearTimeout(timer!);request.abortSignal?.removeEventListener("abort",cancel);} }
}
