import type { GraphDiagnostics, GraphEdge, GraphNeighborhood, GraphNode, GraphSnapshot, GraphTraversalOptions, IRelationshipGraph } from "@/contracts/graph";
const defaults: Required<Pick<GraphTraversalOptions, "maxNodes" | "maxEdges">> = { maxNodes: 100, maxEdges: 200 };
export class RelationshipGraph implements IRelationshipGraph {
  private readonly nodes = new Map<string, GraphNode>(); private readonly edges = new Map<string, GraphEdge>(); private readonly unresolved: Array<{ from: string; type: string; targetLabel: string; source: string }> = []; private readonly diagnostics: GraphDiagnostics = { invalidNodes: 0, invalidEdges: 0, selfLoopsRejected: 0, unresolvedReferences: 0, duplicateNodeMerges: 0, duplicateEdgeMerges: 0, provisionalNodes: 0, cyclesEncountered: 0, traversalTruncations: 0, sourceContributionCount: 0 };
  addUnresolved(reference: { from: string; type: string; targetLabel: string; source: string }) { this.unresolved.push({ ...reference }); this.diagnostics.unresolvedReferences++; }
  addNode(node: GraphNode) { if (!node.id || !node.canonicalId) { this.diagnostics.invalidNodes++; return; } const current = this.nodes.get(node.id); if (current) { this.nodes.set(node.id, { ...current, sourceIds: [...new Set([...current.sourceIds, ...node.sourceIds])].sort(), providerIds: [...new Set([...current.providerIds, ...node.providerIds])].sort(), aliases: [...new Set([...current.aliases, ...node.aliases])].sort(), provenance: [...current.provenance, ...node.provenance] }); this.diagnostics.duplicateNodeMerges++; return; } this.nodes.set(node.id, { ...node, sourceIds: [...node.sourceIds], providerIds: [...node.providerIds], aliases: [...node.aliases], provenance: [...node.provenance] }); if (node.provisional) this.diagnostics.provisionalNodes++; }
  addEdge(edge: GraphEdge) { if (!edge.id || !this.nodes.has(edge.from) || !this.nodes.has(edge.to)) { this.diagnostics.invalidEdges++; return; } if (edge.from === edge.to) { this.diagnostics.selfLoopsRejected++; return; } const current = this.edges.get(edge.id); if (current) { this.edges.set(edge.id, { ...current, provenance: [...current.provenance, ...edge.provenance] }); this.diagnostics.duplicateEdgeMerges++; return; } this.edges.set(edge.id, { ...edge, provenance: [...edge.provenance] }); }
  getNode(id: string) { const node = this.nodes.get(id); return node ? this.cloneNode(node) : undefined; } getEdge(id: string) { const edge = this.edges.get(id); return edge ? this.cloneEdge(edge) : undefined; }
  incoming(id: string, options: GraphTraversalOptions = {}) { return this.filterEdges([...this.edges.values()].filter((edge) => edge.to === id), options); } outgoing(id: string, options: GraphTraversalOptions = {}) { return this.filterEdges([...this.edges.values()].filter((edge) => edge.from === id), options); }
  neighbors(id: string, options: GraphTraversalOptions = {}): GraphNeighborhood { const edges = this.filterEdges([...this.edges.values()].filter((edge) => edge.from === id || edge.to === id), options).slice(0, options.maxEdges ?? defaults.maxEdges); const nodeIds = new Set([id, ...edges.flatMap((edge) => [edge.from, edge.to])]); const nodes = [...nodeIds].map((nodeId) => this.nodes.get(nodeId)).filter((node): node is GraphNode => Boolean(node)).filter((node) => !options.entityTypes || options.entityTypes.includes(node.entityType)).sort((a, b) => a.id.localeCompare(b.id)).slice(0, options.maxNodes ?? defaults.maxNodes).map((node) => this.cloneNode(node)); const counts = Object.fromEntries(edges.reduce((map, edge) => map.set(edge.type, (map.get(edge.type) ?? 0) + 1), new Map<string, number>())); return { center: this.getNode(id), nodes, edges: edges.map((edge) => this.cloneEdge(edge)), relationshipCounts: counts, truncated: edges.length < this.filterEdges([...this.edges.values()].filter((edge) => edge.from === id || edge.to === id), options).length, diagnostics: [] }; }
  snapshot(sourceContextSnapshot?: string): GraphSnapshot { const nodes = [...this.nodes.values()].sort((a, b) => a.id.localeCompare(b.id)).map((node) => Object.freeze(this.cloneNode(node))); const edges = [...this.edges.values()].sort((a, b) => a.id.localeCompare(b.id)).map((edge) => Object.freeze(this.cloneEdge(edge))); const entityCounts: Record<string, number> = {}; const relationshipCounts: Record<string, number> = {}; nodes.forEach((node) => { entityCounts[node.entityType] = (entityCounts[node.entityType] ?? 0) + 1; }); edges.forEach((edge) => { relationshipCounts[edge.type] = (relationshipCounts[edge.type] ?? 0) + 1; }); return Object.freeze({ id: `graph-${nodes.length}-${edges.length}`, createdAt: new Date().toISOString(), nodes: Object.freeze(nodes), edges: Object.freeze(edges), sourceContextSnapshot, unresolvedReferences: Object.freeze(this.unresolved.map((item) => Object.freeze({ ...item }))), diagnostics: Object.freeze({ ...this.diagnostics }), statistics: Object.freeze({ nodeCount: nodes.length, edgeCount: edges.length, entityCounts, relationshipCounts, sourceProviderCount: new Set(nodes.flatMap((node) => node.providerIds)).size }) }); }
  private filterEdges(edges: GraphEdge[], options: GraphTraversalOptions) { return edges.filter((edge) => !options.relationshipTypes || options.relationshipTypes.includes(edge.type)).sort((a, b) => a.id.localeCompare(b.id)); } private cloneNode(node: GraphNode): GraphNode { return { ...node, sourceIds: [...node.sourceIds], providerIds: [...node.providerIds], aliases: [...node.aliases], provenance: node.provenance.map((item) => ({ ...item, temporalEvidence: item.temporalEvidence ? Object.freeze([...item.temporalEvidence]) : undefined })), metadata: node.metadata ? { ...node.metadata } : undefined }; } private cloneEdge(edge: GraphEdge): GraphEdge { return { ...edge, provenance: edge.provenance.map((item) => ({ ...item, temporalEvidence: item.temporalEvidence ? Object.freeze([...item.temporalEvidence]) : undefined })), metadata: edge.metadata ? { ...edge.metadata } : undefined }; }
}
