import type { ISearchService, SearchContext, SearchQuery, SearchResponse, SearchResult, SearchProviderDiagnostic, SearchProviderResponse } from "@/contracts/search";
import { SearchCache } from "./SearchCache";
import { SearchRanking } from "./SearchRanking";
import { SearchRegistry } from "./SearchRegistry";
import type { ITelemetryService } from "@/contracts/telemetry";

export type SearchServiceConfig = { providerTimeoutMs: number; globalTimeoutMs: number; cacheTtlMs: number; maxResultsPerProvider: number; maxMergedResults: number };
const defaults: SearchServiceConfig = { providerTimeoutMs: 2_000, globalTimeoutMs: 3_000, cacheTtlMs: 45_000, maxResultsPerProvider: 50, maxMergedResults: 100 };
export class SearchService implements ISearchService {
  constructor(private readonly registry: SearchRegistry, private readonly ranking = new SearchRanking(), private readonly cache = new SearchCache<SearchResult[]>(), private readonly telemetry?: ITelemetryService, private readonly config: SearchServiceConfig = defaults) {}
  async search(query: SearchQuery): Promise<SearchResponse> {
    const started = Date.now(); const text = query.text.trim(); if (!text) return this.empty(started, "miss");
    const key = `${text.toLowerCase()}|${query.context?.module ?? ""}|${query.context?.projectId ?? ""}`; const cached = this.cache.get(key); if (cached) return { results: cached, providers: [], diagnostics: this.diagnostics(started, [], [], cached.length, 0, 0, 0, "hit") };
    const selected = this.registry.discover("search").filter((provider) => provider.supports({ ...query, text })); const controller = new AbortController(); const external = query.context?.signal; const abort = () => controller.abort(); external?.addEventListener("abort", abort, { once: true }); const globalTimer = setTimeout(() => controller.abort(), this.config.globalTimeoutMs);
    const settled = await Promise.all(selected.map((provider) => this.runProvider(provider.id, provider.search({ ...query, text }, query.context ?? {}, controller.signal), controller.signal))); clearTimeout(globalTimer); external?.removeEventListener("abort", abort);
    const diagnostics = settled.map((item) => item.diagnostic); const merged = this.dedupe(settled.flatMap((item) => item.response.results)); const ranked = this.ranking.rank(merged, { ...query, text }).slice(0, this.config.maxMergedResults); this.cache.set(key, ranked, { ttlMs: this.config.cacheTtlMs, maxEntries: 100 }, selected.map((provider) => provider.id)); const errors = diagnostics.filter((item) => ["error", "timeout"].includes(item.status)).length; const partial = diagnostics.filter((item) => item.status !== "ready").length;
    this.telemetry?.record({ name: "enterprise.search", timestamp: Date.now(), attributes: { queryLength: text.length, providerCount: selected.length, resultCount: ranked.length, errorCount: errors } }); return { results: ranked, providers: diagnostics, diagnostics: this.diagnostics(started, selected.map((p) => p.id), diagnostics.filter((d) => d.status === "ready").map((d) => d.providerId), ranked.length, partial, diagnostics.filter((d) => d.status === "timeout").length, errors, "miss") };
  }
  private async runProvider(providerId: string, task: Promise<SearchProviderResponse>, signal: AbortSignal) { const started = Date.now(); let response: SearchProviderResponse; try { response = await new Promise<SearchProviderResponse>((resolve) => { let settled = false; const timer = setTimeout(() => finish({ status: "timeout", results: [], durationMs: Date.now() - started, diagnostic: "Provider timeout" }), this.config.providerTimeoutMs); const onAbort = () => finish({ status: "cancelled", results: [], durationMs: Date.now() - started, diagnostic: "Search cancelled" }); const finish = (next: SearchProviderResponse) => { if (settled) return; settled = true; clearTimeout(timer); signal.removeEventListener("abort", onAbort); resolve(next); }; signal.addEventListener("abort", onAbort, { once: true }); task.then(finish).catch((error: unknown) => finish({ status: "error", results: [], durationMs: Date.now() - started, diagnostic: error instanceof Error ? error.message : "Provider error" })); }); } catch (error) { response = { status: "error", results: [], durationMs: Date.now() - started, diagnostic: error instanceof Error ? error.message : "Provider error" }; } return { response, diagnostic: { providerId, status: response.status, durationMs: response.durationMs || Date.now() - started, resultCount: response.results.length, diagnostic: response.diagnostic } as SearchProviderDiagnostic }; }
  private dedupe(results: SearchResult[]) { const seen = new Map<string, SearchResult>(); for (const result of results) { const key = result.canonicalUri ?? result.key; const current = seen.get(key); seen.set(key, current ? { ...current, metadata: { ...current.metadata, ...result.metadata }, relationships: [...(current.relationships ?? []), ...(result.relationships ?? [])] } : result); } return [...seen.values()]; }
  private diagnostics(started: number, selected: string[], completed: string[], count: number, partial: number, timeout: number, errors: number, cache: "hit" | "miss") { return { queryId: "q-" + started.toString(36), providersSelected: selected, providersCompleted: completed, durationMs: Date.now() - started, resultCount: count, partialResultCount: partial, timeoutCount: timeout, errorCount: errors, cache }; }
  private empty(started: number, cache: "hit" | "miss"): SearchResponse { return { results: [], providers: [], diagnostics: this.diagnostics(started, [], [], 0, 0, 0, 0, cache) }; }
}
