import type { ContextContribution, ContextRelationship, ContextSignal, ContextSnapshot, EnterpriseContext, IContextEngine, IContextResolver } from "@/contracts/context";
import type { TemporalEvidence } from "@/contracts/temporal";
import { summarizeTemporalEvidence } from "@/services/temporal/TemporalEvidence";
import { EntityResolver } from "./EntityResolver";
export class ContextEngine implements IContextEngine {
  constructor(private readonly resolvers: IContextResolver[] = [], private readonly entityResolver = new EntityResolver(), private readonly clock = () => new Date().toISOString()) {}
  async resolve(context: EnterpriseContext): Promise<ContextContribution[]> { const results = await Promise.all(this.resolvers.filter((resolver) => resolver.canResolve(context)).map((resolver) => resolver.resolve(context))); return results.flat(); }
  async snapshot(context: EnterpriseContext, supplied: ContextContribution[] = []): Promise<ContextSnapshot> { const contributions = [...this.runtimeContributions(context), ...await this.resolve(context), ...supplied]; const entities = this.entityResolver.resolve(contributions); const relationships = this.expandOneLevel(contributions, entities.map((entity) => entity.id)); const signals = this.signals(context); const temporalEvidence = this.temporalEvidence(contributions); return Object.freeze({ context: Object.freeze({ ...context }), entities: Object.freeze(entities), relationships: Object.freeze(relationships), signals: Object.freeze(signals), contributions: Object.freeze(contributions.map((item) => Object.freeze({ ...item, temporalEvidence: item.temporalEvidence ? Object.freeze([...item.temporalEvidence]) : undefined }))), temporalEvidence, temporalStatistics: summarizeTemporalEvidence(temporalEvidence), createdAt: this.clock() }); }
  private runtimeContributions(context: EnterpriseContext): ContextContribution[] { return [{ source: "runtime", label: "Module", value: context.module ?? "", confidence: 0.9 }, { source: "runtime", label: "Project", value: context.projectId ?? "", confidence: 0.9, entityId: context.projectId }, { source: "runtime", label: "Asset", value: context.assetId ?? "", confidence: 0.9, entityId: context.assetId }].filter((item) => item.value) as ContextContribution[]; }
  private signals(context: EnterpriseContext): ContextSignal[] { return Object.entries({ module: context.module, page: context.page, project: context.projectId, asset: context.assetId, selected: context.selectedEntityId }).filter(([, value]) => Boolean(value)).map(([key, value]) => ({ scope: key === "project" ? "project" : key === "asset" ? "asset" : key === "page" ? "page" : "module", source: "runtime", key, value: value as string, weight: 1 })); }
  private temporalEvidence(contributions: ContextContribution[]) { const evidence = new Map<string, TemporalEvidence>(); contributions.flatMap((contribution) => contribution.temporalEvidence ?? []).forEach((item) => evidence.set(item.id, item)); return Object.freeze([...evidence.values()].sort((a, b) => a.id.localeCompare(b.id))); }
  private expandOneLevel(contributions: ContextContribution[], entityIds: string[]): ContextRelationship[] { const known = new Set(entityIds); return contributions.flatMap((contribution) => contribution.relationships ?? []).filter((relationship) => known.has(relationship.from) || known.has(relationship.to)).sort((a, b) => `${a.from}:${a.to}:${a.type}`.localeCompare(`${b.from}:${b.to}:${b.type}`)); }
}
