import type { AIContextPackagePolicy } from "@/contracts/ai-context";
import type { AIExecutionDiagnostic, AIExecutionLimits, AIExecutionPolicy, AIExecutionRequest, AIModelDescriptor, AIModelEligibility, AIModelRegistrySnapshot, AIModelSelection, AIOrchestratorBuildResult } from "@/contracts/orchestrator";
const freeze = <T>(v:T):T => { if(v && typeof v === "object" && !Object.isFrozen(v)){Object.freeze(v); Object.values(v as Record<string,unknown>).forEach(freeze);} return v; };
const sorted = <T extends string>(items: readonly T[]) => [...new Set(items)].sort();
export const defaultAIExecutionPolicy: AIExecutionPolicy = freeze({ allowLocalModels:true, allowPrivateCloudModels:false, allowPublicCloudModels:false, allowExternalKnowledge:false, allowToolUse:false, allowStreaming:false, allowBatch:false, allowVision:false, allowAudio:false, allowVideo:false, allowSensitiveData:false, requireCitations:true, requireEvidenceTraceability:true, requireUncertaintyDisclosure:true, requireStructuredOutput:false, requireLocalOnly:true, preferredLocations:["local"], blockedProviderTypes:[], blockedModelIds:[], allowedModelIds:[], preferredModelIds:[], fallbackAllowed:true, maxFallbackCandidates:2, costPreference:"balanced", latencyPreference:"balanced", reasoningPreference:"neutral" });
export const defaultAIExecutionLimits: AIExecutionLimits = freeze({ maxCandidateModels:20,maxFallbackCandidates:2,maxPlanningDiagnostics:100,maxRequiredCapabilities:20,maxPreferredCapabilities:20,maxAllowedModels:50,maxBlockedModels:50,maxExecutionSteps:1,timeoutMs:120000,maxRetries:0 });
const policy = (base: AIContextPackagePolicy, request?: Partial<AIExecutionPolicy>): AIExecutionPolicy => freeze({ ...defaultAIExecutionPolicy, ...request, allowExternalKnowledge: false, allowToolUse: false, allowSensitiveData: Boolean(request?.allowSensitiveData && base.allowSensitiveData), requireCitations: base.requireCitations || request?.requireCitations !== false, requireEvidenceTraceability: base.requireEvidenceTraceability || request?.requireEvidenceTraceability !== false, requireUncertaintyDisclosure: base.requireUncertaintyDisclosure || request?.requireUncertaintyDisclosure !== false, preferredLocations: sorted(request?.preferredLocations ?? defaultAIExecutionPolicy.preferredLocations), blockedProviderTypes: sorted(request?.blockedProviderTypes ?? []), blockedModelIds: sorted(request?.blockedModelIds ?? []), allowedModelIds: sorted(request?.allowedModelIds ?? []), preferredModelIds: sorted(request?.preferredModelIds ?? []) });
const limits = (input?: Partial<AIExecutionLimits>): AIExecutionLimits => { const merged={...defaultAIExecutionLimits,...input}; if(Object.values(merged).some(v=>typeof v === "number" && (!Number.isFinite(v)||v<0))) throw new Error("Invalid execution limits"); return freeze(merged); };
export class AIModelOrchestrator {
  build(request: AIExecutionRequest, registry: AIModelRegistrySnapshot): AIOrchestratorBuildResult {
    const diagnostics: AIExecutionDiagnostic[]=[]; if(request.signal?.aborted) return freeze({status:"cancelled",diagnostics:[{code:"planning-cancelled",message:"Planning cancelled"}],eligibility:[]});
    if(request.contextPackageId!==request.contextPackage.id || request.contextFingerprint!==request.contextPackage.sourceFingerprint || request.registryId!==registry.registryId || request.registryVersion!==registry.version) return freeze({status:"stale",diagnostics:[{code:"stale-input",message:"Context package or registry reference is stale"}],eligibility:[]});
    if(request.contextPackage.diagnostics.some(d=>d.code === "package-build-failed") || !["ready","ready-partial","ready-empty"].includes((request.contextPackage as unknown as {status?:string}).status ?? "ready")) return freeze({status:"failed",diagnostics:[{code:"invalid-context-package",message:"Context package is not usable"}],eligibility:[]});
    let effective: AIExecutionPolicy; let bounded: AIExecutionLimits; try { effective=policy(request.contextPackage.policy,request.policy); bounded=limits(request.limits); } catch { return freeze({status:"invalid-request",diagnostics:[{code:"invalid-limits",message:"Execution limits are invalid"}],eligibility:[]}); }
    const mode=request.mode ?? "synchronous"; if((mode==="streaming"&&!effective.allowStreaming)||(mode==="batch"&&!effective.allowBatch)) return freeze({status:"policy-rejected",diagnostics:[{code:"mode-disallowed",message:"Execution mode is disallowed by policy"}],eligibility:[]});
    const candidates=registry.models.slice(0,bounded.maxCandidateModels); const eligibility=candidates.map(model=>this.eligible(model,request,effective,mode)); const selected=eligibility.filter(x=>x.eligible).sort((a,b)=>b.score-a.score || a.modelId.localeCompare(b.modelId));
    if(!selected.length) return freeze({status:"no-eligible-model",diagnostics:[{code:"no-eligible-model",message:"No registry model satisfies the request and policy"}],eligibility});
    const toSelection=(x:AIModelEligibility):AIModelSelection=>{ const model=registry.models.find(item=>item.identity.modelId===x.modelId); if(!model) throw new Error("Eligible model missing from registry"); return freeze({modelId:x.modelId,providerType:model.providerType,location:model.location,score:x.score,reasons:x.reasons}); }; const primary=toSelection(selected[0]); const fallbacks=effective.fallbackAllowed ? selected.slice(1,1+Math.min(effective.maxFallbackCandidates,bounded.maxFallbackCandidates)).map(toSelection):[];
    const fingerprint=`ai-plan-1:${request.requestId}:${request.contextFingerprint}:${registry.sourceFingerprint}:${primary.modelId}:${fallbacks.map(x=>x.modelId).join(",")}`;
    return freeze({status:fallbacks.length?"ready-with-fallbacks":"ready",plan:{id:`ai-plan:${fingerprint}`,fingerprint,contextPackageId:request.contextPackage.id,contextFingerprint:request.contextPackage.sourceFingerprint,registryId:registry.registryId,registryVersion:registry.version,task:request.task,status:fallbacks.length?"ready-with-fallbacks":"ready",policy:effective,limits:bounded,primary,fallbacks:{candidates:fallbacks},steps:[{type:"model-execution",modelId:primary.modelId,outputType:request.task.outputType,mode}],diagnostics,statistics:{candidateCount:candidates.length,eligibleCount:selected.length,rejectionCount:eligibility.length-selected.length,fallbackCount:fallbacks.length,durationMs:0}},diagnostics,eligibility});
  }
  private eligible(m:AIModelDescriptor,r:AIExecutionRequest,p:AIExecutionPolicy,mode:string):AIModelEligibility { const reasons:string[]=[]; const task=r.task; const require=(v:boolean,c:string)=>{if(!v)reasons.push(c);}; const locationAllowed = m.location === "local" ? p.allowLocalModels : m.location === "private-cloud" ? p.allowPrivateCloudModels : m.location === "public-cloud" ? p.allowPublicCloudModels : !p.requireLocalOnly; require(m.enabled,"disabled"); require(m.availability==="available" || m.availability==="degraded","unavailable"); require(!p.blockedModelIds.includes(m.identity.modelId),"blocked-model"); require(!p.blockedProviderTypes.includes(m.providerType),"blocked-provider"); require(!p.allowedModelIds.length||p.allowedModelIds.includes(m.identity.modelId),"not-allowlisted"); require(locationAllowed && (!p.requireLocalOnly || m.location === "local"),"location-disallowed"); require(m.capabilities.modalitySupport.includes(task.inputModality),"input-modality"); require(m.supportedOutputTypes.includes(task.outputType),"output-type"); require(m.supportedExecutionModes.includes(mode as "synchronous"),"execution-mode"); for(const cap of task.requiredCapabilities) require(m.capabilities.supported.includes(cap),`capability:${cap}`); if(task.requiresCitations||p.requireCitations) require(m.capabilities.supported.includes("citations"),"citations"); if(task.requiresStructuredOutput||p.requireStructuredOutput) require(m.capabilities.supported.includes("structured-output")||m.capabilities.supported.includes("JSON-output"),"structured-output"); if(task.requiresReasoning||task.type==="reasoning"||p.reasoningPreference==="required") require(m.capabilities.supported.includes("reasoning"),"reasoning"); if(task.language) require(m.languages.languages.includes(task.language),"language"); if(task.requiresLongContext) require(m.contextProfile.supportsLongContext,"long-context"); const score=m.priority*100+(p.preferredModelIds.includes(m.identity.modelId)?10000:0)+(m.supportedTasks.includes(task.type)?100:0)+task.preferredCapabilities.filter(c=>m.capabilities.supported.includes(c)).length*10+(m.location==="local"?5:0); return freeze({modelId:m.identity.modelId,eligible:!reasons.length,score,reasons:sorted(reasons)}); }
}
