import type { AIExecutionMode, AIExecutionPlan, AIExecutionOutputType, AIExecutionPolicy, AIExecutionTask, AIModelLocation, AIModelProviderType } from "@/contracts/orchestrator";

export type AIModelRuntimeStatus = "idle" | "validating" | "resolving-adapter" | "executing" | "retrying" | "falling-back" | "succeeded" | "failed" | "timed-out" | "cancelled" | "stale" | "rejected";
export type AIModelRuntimeAttemptStatus = "pending" | "executing" | "succeeded" | "failed" | "timed-out" | "cancelled" | "skipped" | "incompatible-adapter";
export type AIModelAdapterErrorCategory = "validation" | "unavailable" | "timeout" | "cancellation" | "transport" | "authentication" | "authorization" | "rate-limit" | "capacity" | "malformed-response" | "unsupported" | "provider-error" | "unknown";
export type AIModelAdapterError = Readonly<{ code: string; category: AIModelAdapterErrorCategory; retryable: boolean; fallbackEligible: boolean; message: string; providerCode?: string; safeDetails?: Readonly<Record<string, string>> }>;
export type AIModelAdapterDescriptor = Readonly<{ adapterId: string; adapterVersion: string; providerType: AIModelProviderType; supportedModelIds: readonly string[]; supportedLocations: readonly AIModelLocation[]; supportedExecutionModes: readonly AIExecutionMode[]; supportsCancellation: boolean; supportsTimeout: boolean; supportsStreaming: boolean; supportsBatch: boolean; enabled: boolean; priority: number; metadata?: Readonly<Record<string, string>> }>;
export type AIModelAdapterRequest = Readonly<{ executionId: string; attemptId: string; requestId: string; planId: string; modelId: string; providerType: AIModelProviderType; task: AIExecutionTask; expectedOutputType: AIExecutionOutputType; executionMode: AIExecutionMode; contextPackageReference: Readonly<{ id: string; fingerprint: string }>; effectivePolicy: AIExecutionPolicy; limits: Readonly<{ timeoutMs: number; maxOutputCharacters: number }>; adapterInput: Readonly<{ taskType: string; inputModality: string; outputType: string; contextPackageId: string; contextPackageFingerprint: string; normalizedInputReference?: string; inputText?: string; messages?: readonly Readonly<{ role: "system" | "user" | "assistant"; content: string }>[]; generationParameters?: Readonly<{ temperature?: number; topP?: number; topK?: number; seed?: number; numPredict?: number; repeatPenalty?: number; stop?: readonly string[] }>; structuredParameters: Readonly<Record<string, string | number | boolean>>; language?: string; citationRequirement: boolean; evidenceTraceabilityRequirement: boolean }>; metadata: Readonly<Record<string, string>>; signal: AbortSignal }>;
export type AIModelNormalizedOutput = Readonly<{ outputType: AIExecutionOutputType; text?: string; structuredData?: Readonly<Record<string, string | number | boolean | null>>; references: readonly string[]; citations: readonly Readonly<{ id: string; reference: string }>[]; finishReason: "completed" | "length" | "cancelled" | "unknown"; modelMetadata: Readonly<Record<string, string>> }>;
export type AIModelAdapterResult = Readonly<{ status: "succeeded" | "failed" | "timed-out" | "cancelled" | "rejected"; adapterId: string; modelId: string; output?: AIModelNormalizedOutput; error?: AIModelAdapterError; diagnostics: readonly AIModelRuntimeDiagnostic[]; usage?: Readonly<{ inputTokens?: number; outputTokens?: number; totalTokens?: number; estimated: boolean; providerReported: boolean }>; metadata: Readonly<Record<string, string>>; startedAt: string; completedAt: string; durationMs: number }>;
export interface AIModelAdapter { readonly descriptor: AIModelAdapterDescriptor; supports(request: Readonly<{ modelId: string; providerType: AIModelProviderType; location: AIModelLocation; mode: AIExecutionMode }>): boolean; execute(request: AIModelAdapterRequest): Promise<AIModelAdapterResult>; }
export type AIModelAdapterRegistrySnapshot = Readonly<{ registryId: string; version: string; adapters: readonly AIModelAdapterDescriptor[]; sourceFingerprint: string }>;
export type AIModelRuntimePolicy = Readonly<{ allowExecution: boolean; allowRetries: boolean; allowFallbacks: boolean; allowStreaming: boolean; allowBatch: boolean; allowDegradedAdapters: boolean; stopOnCancellation: boolean; stopOnTimeout: boolean; retryableErrorCategories: readonly AIModelAdapterErrorCategory[]; fallbackEligibleErrorCategories: readonly AIModelAdapterErrorCategory[]; requirePlanPolicyCompliance: boolean; requireAdapterCompatibility: boolean; requireSourceValidation: boolean }>;
export type AIModelRuntimeLimits = Readonly<{ timeoutMs: number; maxRetriesPerModel: number; maxTotalAttempts: number; maxFallbackAttempts: number; maxDiagnostics: number; maxAttemptRecords: number; maxOutputCharacters: number; maxStructuredOutputBytes: number; maxCitationCount: number }>;
export type AIModelRuntimeDiagnostic = Readonly<{ code: string; message: string; attemptId?: string; modelId?: string; category?: AIModelAdapterErrorCategory }>;
export type AIModelRuntimeAttempt = Readonly<{ attemptId: string; sequence: number; modelId: string; adapterId?: string; status: AIModelRuntimeAttemptStatus; retryIndex: number; fallbackIndex: number; error?: AIModelAdapterError; usage?: AIModelAdapterResult["usage"]; durationMs: number }>;
export type AIModelRuntimeRequest = Readonly<{ executionId: string; executionPlan: AIExecutionPlan; expectedPlanId?: string; expectedPlanFingerprint?: string; expectedContextPackageId?: string; expectedRegistryVersion?: string; adapterRegistry: AIModelAdapterRegistrySnapshot; runtimePolicy?: Partial<AIModelRuntimePolicy>; runtimeLimits?: Partial<AIModelRuntimeLimits>; adapterInput: AIModelAdapterRequest["adapterInput"]; abortSignal?: AbortSignal }>;
export type AIModelRuntimeResult = Readonly<{ executionId: string; status: AIModelRuntimeStatus; planId: string; planFingerprint: string; completedModelId?: string; completedAdapterId?: string; output?: AIModelNormalizedOutput; attempts: readonly AIModelRuntimeAttempt[]; diagnostics: readonly AIModelRuntimeDiagnostic[]; statistics: Readonly<{ plannedModelCount: number; attemptCount: number; retryCount: number; fallbackCount: number; successCount: number; failureCount: number; durationMs: number }>; metadata: Readonly<{ adapterRegistryId: string; adapterRegistryVersion: string }>; fingerprint: string }>;
