import type { ContextSnapshot } from "@/contracts/context";
import type { MemorySnapshot } from "@/contracts/memory";
import type { GraphRuntimeSession } from "@/contracts/graph/runtime";
import { MemoryContributionAdapter } from "./MemoryContributionAdapter";
import { MemoryBuilder } from "./MemoryBuilder";
import { summarizeTemporalEvidence } from "@/services/temporal/TemporalEvidence";
import type { ITelemetryService } from "@/contracts/telemetry";
export type MemoryRuntimeStatus = "idle" | "building" | "ready" | "ready-empty" | "stale" | "failed" | "cancelled";
export type MemoryRuntimeSession = Readonly<{ sessionId: string; version: number; status: MemoryRuntimeStatus; sourceContextSnapshotId: string; sourceGraphSessionId: string; memorySnapshot: MemorySnapshot; temporalStatistics: ReturnType<typeof summarizeTemporalEvidence>; createdAt: string; completedAt: string; buildKey: string; diagnostics: readonly string[] }>;
export type MemoryRuntimeResult = Readonly<{ session?: MemoryRuntimeSession; status: MemoryRuntimeStatus; diagnostics: readonly string[] }>;
export class MemoryRuntimeService { private session?: MemoryRuntimeSession; private version = 0; constructor(private readonly adapter = new MemoryContributionAdapter(), private readonly builder = new MemoryBuilder(), private readonly clock = () => new Date().toISOString(), private readonly telemetry?: ITelemetryService) {} current() { return this.session; } async build(context: ContextSnapshot, graph: GraphRuntimeSession, signal?: AbortSignal): Promise<MemoryRuntimeResult> { const key = `${context.createdAt}|${graph.sessionId}|runtime-1`; if (this.session?.buildKey === key) return { session: this.session, status: this.session.status, diagnostics: Object.freeze(["Memory build reused"]) }; const version = ++this.version; if (signal?.aborted) return { status: "cancelled", diagnostics: Object.freeze(["Memory build cancelled"]) }; try { const adapted = this.adapter.adapt(context, graph); if (signal?.aborted) return { status: "cancelled", diagnostics: Object.freeze(["Memory build cancelled"]) }; const snapshot = this.builder.build({ contributions: adapted.contributions, diagnostics: adapted.diagnostics, graphSessionId: graph.sessionId, sourceContextSnapshotId: `context-${context.createdAt}`, createdAt: this.clock() }); if (signal?.aborted) return { status: "cancelled", diagnostics: Object.freeze(["Memory build cancelled"]) }; if (version !== this.version) return { status: "stale", diagnostics: Object.freeze(["Stale memory build rejected"]) }; const status: MemoryRuntimeStatus = snapshot.observations.length ? "ready" : "ready-empty"; const temporalStatistics = summarizeTemporalEvidence(context.temporalEvidence, { observationsCreated: snapshot.observations.length, status }); const session = Object.freeze({ sessionId: `memory-session-${version}`, version, status, sourceContextSnapshotId: `context-${context.createdAt}`, sourceGraphSessionId: graph.sessionId, memorySnapshot: snapshot, temporalStatistics, createdAt: snapshot.metadata.createdAt, completedAt: snapshot.metadata.createdAt, buildKey: key, diagnostics: Object.freeze([...snapshot.diagnostics.messages]) }); this.recordTelemetry(status === "ready" ? "memory_runtime_ready" : "memory_runtime_ready_empty", { evidenceCount: temporalStatistics.evidenceCount, observationCount: temporalStatistics.observationsCreated, providerCount: temporalStatistics.providerCount }); this.session = session; return { session, status, diagnostics: session.diagnostics }; } catch { return { status: "failed", diagnostics: Object.freeze(["Memory build failed"]) }; } } private recordTelemetry(name: string, attributes: Record<string, number>) { try { this.telemetry?.record({ name, timestamp: Date.now(), attributes }); } catch { /* Telemetry is optional and cannot affect memory construction. */ } } invalidate() { this.session = undefined; } reset() { this.session = undefined; this.version = 0; } }
