import type { ContextSnapshot } from "@/contracts/context";
import type { GraphRuntimeDiagnostics, GraphRuntimeResult, GraphRuntimeSession, IGraphRuntimeService } from "@/contracts/graph/runtime";
import type { GraphPath, GraphTraversalOptions } from "@/contracts/graph";
import { graphFromContext } from "../ContextGraphAdapter";
import { GraphQueryEngine } from "../GraphQueryEngine";
import { RelationshipGraph } from "../RelationshipGraph";
export class GraphRuntimeService implements IGraphRuntimeService {
  private session?: GraphRuntimeSession; private graph?: RelationshipGraph; private version = 0;
  current() { return this.session; }
  async build(snapshot: ContextSnapshot, signal?: AbortSignal): Promise<GraphRuntimeResult> { const sourceId = `context-${snapshot.createdAt}`; if (this.session?.sourceContextSnapshotId === sourceId) return { session: this.session, status: "ready", diagnostics: { ...this.session.diagnostics, reused: true } }; const requestVersion = ++this.version; const base: GraphRuntimeDiagnostics = { sourceContextSnapshotId: sourceId, requestVersion, acceptedVersion: this.session?.version ?? 0, reused: false, staleRejected: false, cancelled: false, failed: false, previousSessionRetained: Boolean(this.session) }; if (signal?.aborted) return { status: "cancelled", diagnostics: { ...base, cancelled: true, message: "Graph build cancelled" } }; try { const snapshotGraph = graphFromContext(snapshot); if (signal?.aborted) return { status: "cancelled", diagnostics: { ...base, cancelled: true, message: "Graph build cancelled" } }; if (requestVersion !== this.version) return { status: "stale", diagnostics: { ...base, staleRejected: true, message: "Stale graph build rejected" } }; const graph = new RelationshipGraph(); snapshotGraph.nodes.forEach((node) => graph.addNode(node)); snapshotGraph.edges.forEach((edge) => graph.addEdge(edge)); snapshotGraph.unresolvedReferences.forEach((reference) => graph.addUnresolved(reference)); const graphSnapshot = graph.snapshot(sourceId); const session: GraphRuntimeSession = Object.freeze({ sessionId: `graph-session-${requestVersion}`, version: requestVersion, sourceContextSnapshotId: sourceId, sourceContextTimestamp: snapshot.createdAt, graphSnapshot, status: "ready", createdAt: snapshot.createdAt, completedAt: snapshot.createdAt, diagnostics: Object.freeze({ ...base, acceptedVersion: requestVersion, previousSessionRetained: false }), nodeCount: graphSnapshot.statistics.nodeCount, edgeCount: graphSnapshot.statistics.edgeCount, unresolvedReferenceCount: graphSnapshot.unresolvedReferences.length, provisionalIdentityCount: graphSnapshot.diagnostics.provisionalNodes }); this.graph = graph; this.session = session; return { session, status: "ready", diagnostics: session.diagnostics }; } catch (error) { return { status: "failed", diagnostics: { ...base, failed: true, message: error instanceof Error ? error.message : "Graph build failed" } }; } }
  invalidate(snapshotId?: string) { if (!snapshotId || this.session?.sourceContextSnapshotId === snapshotId) { this.session = undefined; this.graph = undefined; } }
  reset() { this.session = undefined; this.graph = undefined; this.version = 0; }
  neighborhood(nodeId: string, options?: GraphTraversalOptions) { return this.graph ? new GraphQueryEngine(this.graph).traverse(nodeId, options) : undefined; }
  shortestPath(from: string, to: string, options?: GraphTraversalOptions): GraphPath | undefined { return this.graph ? new GraphQueryEngine(this.graph).shortestPath(from, to, options) : undefined; }
}
